# -*- coding: utf-8 -*-
"""t_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZQXZIUzXjQsQ71YyNrSKCDZ33AQ0ejg
"""

import numpy as np
import scipy.stats as stats

data = np.array([
    [0.0008, -0.0014,  0.0031, -0.0004, 0.0083,  6,  -6,  -4],
    [-0.0015, -0.0009, -0.0020, -0.0003, 0.0006, -1,   1,  32],
    [0.0002,  0.0009, -0.0006, -0.0002, 0.0077, 13, -13,  -7],
    [0.0013,  0.0018,  0.0007,  0.0001, 0.0107,  8,  -8, -15],
    [-0.0007, -0.0050,  0.0035, -0.0003, 0.0046, -4,   4,  -4],
    [-0.0005, -0.0015,  0.0004,  0.0000, 0.0036,  3,  -3,  10]
])

metrics = ["F1 Score", "Precision", "Recall", "mAP50", "mAP50-95", "TP", "FN", "FP"]

alpha = 0.05
results = {metric: stats.ttest_1samp(data[:, i], 0) for i, metric in enumerate(metrics)}

for metric, (t_stat, p_value) in results.items():
    print(f"{metric}: t-statistic = {t_stat:.4f}, p-value = {p_value:.4f}")

    if p_value < alpha:
        if t_stat > 0:
            print(f"  ➤ Significant positive difference: YOLOv9 outperforms YOLOv8 in {metric}.\n")
        else:
            print(f"  ➤ Significant negative difference: YOLOv8 outperforms YOLOv9 in {metric}.\n")
    else:
        print(f"  ➤ No significant difference: Performance is statistically similar for {metric}.\n")