# -*- coding: utf-8 -*-
"""Generalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mkP0uKaV58lXY2ThiOibdXa59x-7M9fg

# **Generalization with CORS-ADD-HBB Data**

<p align="center">
    <img src="https://github.com/RSandAI/Comprehensive-YOLO-Airplane-Detection/blob/main/assets/image.png" height=450 width=1280 alt=""/>
</p>

<small>Picture Source: <a href="https://github.com/RSandAI/Comprehensive-YOLO-Airplane-Detection/">RSandAI, Comprehensive YOLO Airplane Detection</a></small>

<br>

## **Context**

The HRPlanes dataset is a valuable resource in the domain of computer vision, particularly for tasks related to object detection, specifically focusing on aircraft within Very High Resolution (VHR) Google Earth images. This dataset comprises 3101 RGB images of major airports and aircraft boneyards, manually annotated with bounding boxes for airplanes using Plainsight (formerly HyperLabel). Quality control was conducted independently, resulting in 18,477 annotated airplanes. The dataset is split into 70% training (2170 images), 20% validation (620 images), and 10% testing (311 images) sets.

<br>

To facilitate accurate training and evaluation, each aircraft within the images has been meticulously labeled, resulting in a comprehensive annotation set covering a total of 18,477 aircraft instances. These annotations provide bounding box coordinates for each detected aircraft within the corresponding images.

<br>

## **Generalization with CORS-ADD-HBB Data**

Generalization, the ability of a machine learning model to perform well on unseen data, is a critical aspect of model evaluation. In this study, we aim to assess the generalization performance of our top 2 YOLOv9 models using the CORS-ADD-HBB dataset. The CORS-ADD-HBB dataset, a curated collection of diverse data points, offers a comprehensive testbed for evaluating model robustness and adaptability across various domains. Leveraging this dataset, we seek to explore the extent to which our YOLOv9 models can effectively generalize beyond their training data, providing insights into their real-world applicability and reliability.

**Top 3 Models:**

| Rank | Experiment ID | Model | Network size | Optimizer | Augmentation | F1 Score | Precision | Recall | mAP50 | mAP50-95 |
|--|--|--|--|--|--|--|--|--|--|--|
| 1 | 58 | YOLOv9e | 640x640 | SGD | Hue (0.015) - Saturation (0.7) - Value (0.4) - Mosaic | 0.9917 | 0.9918 | 0.9916 | 0.9937 | 0.8989 |
| 2 | 57 | YOLOv9e | 640x640 | SGD | None | 0.9899 | 0.9912 | 0.9886 | 0.9935 | 0.8982 |
| 3 | 62 | YOLOv9e | 640x640 | ADAMW | Hue (0.015) - Saturation (0.7) - Value (0.4) - Mosaic | 0.9899 | 0.9891 | 0.9907 | 0.9936 | 0.8930 |

<br>

Make sure your runtime is **GPU** (_not_ CPU or TPU). And if it is an option, make sure you are using _Python 3_. You can select these settings by going to `Runtime -> Change runtime type -> Select the above mentioned settings and then press SAVE`.

## **0. Initial Steps**

### **0.1 Download Library**
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/WongKinYiu/yolov9.git
# %cd yolov9
!pip install -r requirements.txt -q

"""### **0.2. Import Libraries and Connect Google Drive**"""

from google.colab import drive
drive.mount('/gdrive')

import shutil

"""### **0.3. Define Paths of Model Weights**"""

# @markdown ---

MODEL_1_PT = '/gdrive/MyDrive/Datasets/HRPlanes/YOLOV8/YOLOv9e/Experiment_No_58/epoch_75_100/runs/train/exp/weights/best.pt' # @param {type:"string"}
MODEL_2_PT = '/gdrive/MyDrive/Datasets/HRPlanes/YOLOV8/YOLOv9e/Experiment_No_57/runs/train/exp/weights/best.pt' # @param {type:"string"}
MODEL_3_PT = '/gdrive/MyDrive/Datasets/HRPlanes/YOLOV8/YOLOv9e/Experiment_No_62/epoch_75_100/runs/train/exp/weights/best.pt' # @param {type:"string"}

"""## **1. Validate Models with CORS-ADD-HBB Data**

The T4 GPU is a powerful graphics processing unit (GPU) developed by NVIDIA. It is part of the NVIDIA Ampere architecture and is designed for high-performance computing tasks, including deep learning, data analytics, and scientific computing. The T4 GPU offers significant improvements in performance and efficiency compared to previous GPU models, making it ideal for demanding AI and machine learning applications.
"""

!nvidia-smi

"""### **1.1. Validate Model 1**"""

!python val_dual.py \
--img 640 --batch 16 \
--data /content/coco_test.yaml \
--weights {MODEL_1_PT}

"""### **1.2. Validate Model 2**"""

!python val_dual.py \
--img 640 --batch 16 \
--data /content/coco_test.yaml \
--weights {MODEL_2_PT}

"""### **1.3. Validate Model 3**"""

!python val_dual.py \
--img 640 --batch 16 \
--data /content/coco_test.yaml \
--weights {MODEL_3_PT}

"""## **3. Move Model Items into Google Drive**

Instead of uploading and downloading files, we can directly move them to the desired path.
"""

shutil.move("/content/yolov9/runs/val/", "/gdrive/MyDrive/Datasets/HRPlanes/YOLOV8/CORS_AD_HBB/YOLOv9 Tests/")

from datetime import datetime
print(f"Changes have been made to the project on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")